In [ ]:
#1. Demonstrate three different methods for creating identical 2D arrays in NumPyƒ Provide the code for each
#method and the final output after each method.

Method 1: Using numpy.array

In [60]:
import numpy as np

# Create a 2D array using np.array
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array1


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Method 2: Using numpy.ones and numpy.full

In [62]:
import numpy as np


# Create a 2D array using np.ones and then multiplying
array2 = np.ones((2, 3), dtype=int) * 1

array2


# Create a 2D array using np.full
array3 = np.full((2, 3), 1)
array3


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
Method 3: Using numpy.zeros and numpy.add

In [64]:
import numpy as np

# Create a 2D array using np.zeros and then adding
array4 = np.zeros(2, 3))
array4


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#2. Using the Numpy function, generate an array of wRR evenly spaced numPers Petween w and wR and
#Reshape that 1D array into a 2D array

import numpy as np
a= np.linspace (1, 10, 100)

In [8]:
a

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [10]:
a.reshape(10,10)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [ ]:
#3. Explain the following termsg
#1. The difference in np.array, np.asarray and np.asanyarray
#2. The difference between Deep copy and shallow copy



np.array: Always creates a new array and can make a copy of the data.
 This function creates an array from any object exposing the array interface, such as lists, tuples, or other arrays. It always makes a copy of the data by default, unless specified otherwise.

In [12]:
#np.array ex:
import numpy as np

# Create a list
list_data = [1, 2, 3, 4]

array_data = np.array(list_data)
print(array_data)


[1 2 3 4]


In [ ]:
np.asarray: This function converts the input to an array, but does not make a copy if the input is already an array (or array-like) with the same data type.

In [14]:
#Ex of np.asarray

import numpy as np

# Create a list
list_data = [1, 2, 3, 4]

# Convert list to array using np.asarray
array_data = np.asarray(list_data)
print("np.asarray from list:\n", array_data)

# Convert array to array using np.asarray (no copy)
array_data_copy = np.asarray(array_data)
print("np.asarray from array (no copy):\n", array_data_copy)


np.asarray from list:
 [1 2 3 4]
np.asarray from array (no copy):
 [1 2 3 4]


In [ ]:
3. np.asanyarray: This function is similar to np.asarray, but it passes through subclasses of ndarray. 
This is useful when you have custom array-like objects that you don't want to convert to a base ndarray object.

In [15]:
#example: np.asanyarray

import numpy as np

# Create a list
list_data = [1, 2, 3, 4]

# Convert list to array using np.asanyarray
array_data = np.asanyarray(list_data)
print("np.asanyarray from list:\n", array_data)

# Convert array to array using np.asanyarray (no copy)
array_data_copy = np.asanyarray(array_data)
print("np.asanyarray from array (no copy):\n", array_data_copy)

# Create a matrix (a subclass of ndarray)
matrix_data = np.matrix(list_data)
print("Matrix data:\n", matrix_data)

# Convert matrix to array using np.asanyarray (preserves subclass)
matrix_data_copy = np.asanyarray(matrix_data)
print("np.asanyarray from matrix (preserves subclass):\n", matrix_data_copy)


np.asanyarray from list:
 [1 2 3 4]
np.asanyarray from array (no copy):
 [1 2 3 4]
Matrix data:
 [[1 2 3 4]]
np.asanyarray from matrix (preserves subclass):
 [[1 2 3 4]]


In [ ]:
 Shallow copy: In this array if we will make the changes in base array then , reference arrayv will also be get updated. This is called Shallow cop.

In [19]:
#ex. of Shallow Copy:

l = [ 'ram', 'shyam', 'mohan', 'radha']
a = l
a
l

['ram', 'shyam', 'mohan', 'radha']

In [20]:
l[0] = 'Ramesh'
l

['Ramesh', 'shyam', 'mohan', 'radha']

In [21]:
a

['Ramesh', 'shyam', 'mohan', 'radha']

In [ ]:
Deep Copy: In this arrasy, if we make changes in the base array then thatv doesn't impact other newly created array. 


In [24]:
#example of deep copy?:
l = [ 'ram', 'shyam', 'mohan', 'radha']
a = l.copy()
l[1] = 'Govind'
l

['ram', 'Govind', 'mohan', 'radha']

In [25]:
a

['ram', 'shyam', 'mohan', 'radha']

In [ ]:
4. Generate a 3x3 array with random floating-point numbers between 5 and 20, then, round each number in
the array to 2 decimal places.

In [28]:
import numpy as np

arr = np.random.uniform(5, 20, (3,3))

In [29]:
arr

array([[18.24360109, 12.63803801,  5.10119791],
       [ 9.66391644,  8.19039771, 10.36940267],
       [11.76156027, 12.98561028,  5.4482742 ]])

In [32]:
rounded_arr = np.round(arr, 2)

In [34]:
rounded_arr

array([[18.24, 12.64,  5.1 ],
       [ 9.66,  8.19, 10.37],
       [11.76, 12.99,  5.45]])

In [ ]:
5. Create a NumPy array with random inmtegers between  1 and 10 of shape(5, 6). After creating the array perform.
perform the following operations:

 a)Extract all even integers from array.

 b)Extract all odd integers from array

In [50]:
import numpy as np

Random_arr = np.random.randint(1, 11, size=(5, 6))
Random_arr

array([[ 6,  8, 10,  1,  6,  1],
       [ 5, 10, 10,  3,  5,  7],
       [ 8,  1,  5,  5,  8,  8],
       [ 4,  9,  1,  9,  8, 10],
       [ 4, 10,  8,  6, 10, 10]])

In [51]:
#a)Extract all even integers from array.

even_int = Random_arr[ Random_arr%2==0]
even_int

array([ 6,  8, 10,  6, 10, 10,  8,  8,  8,  4,  8, 10,  4, 10,  8,  6, 10,
       10])

In [52]:
#b)Extract all odd integers from array.

odd_int = Random_arr[ Random_arr%2!=0]
odd_int

array([1, 1, 5, 3, 5, 7, 1, 5, 5, 9, 1, 9])

In [ ]:
6. Create a 3D Numpy array of shape( 3, 3, 3) containing random integers  between 1 and 10 and   Perform 
a) find the indices of the maximum values along each depth level( third axis)
b) Perform element- wise multiplication of between both array.

In [55]:
#Create a 3D Numpy array of shape( 3, 3, 3) containing random integers  between 1 and 10

import numpy as np

arr = np.random.randint(1, 11, (3, 3, 3))

arr

array([[[ 6,  9,  6],
        [ 1, 10,  1],
        [ 1,  7,  9]],

       [[ 5,  8,  4],
        [ 1,  2,  7],
        [10, 10,  2]],

       [[ 1,  5,  3],
        [ 1,  3,  4],
        [ 4,  7,  9]]])

In [57]:
#a) find the indices of the maximum values along each depth level( third axis)

max_indices = np.argmax(arr, axis=2)
max_indices

array([[1, 1, 2],
       [1, 2, 0],
       [1, 2, 2]])

In [59]:
#b) Perform element- wise multiplication of between both array.

import numpy as np

arr1 = np.random.randint(1, 11, (3, 3, 3))


arr2 = np.random.randint(1, 11, (3, 3, 3))

result= arr1*arr2
result

array([[[18, 20, 36],
        [32, 54,  2],
        [24, 21, 14]],

       [[30,  9, 12],
        [90, 49, 40],
        [ 4, 14, 45]],

       [[42, 40, 10],
        [63, 14, 20],
        [21, 30, 20]]])

In [ ]:
7. Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and
convert it to a numeric data type
Also display the table attribut and data types of each column.


In [68]:
import pandas as pd

pd.read_csv('People Data.csv')

Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                             Email                  Phone Date of birth  \
0              pwarner@example.org           857.139.8239    27-01-2014   
1    fergusonkatherine@example.net                    NaN    26-07-1931   
2              fhoward@example.org          (599)782-0605    25-11-2013   
3            zjohnston@example.com                    NaN    17-11-2012   
4                 elin@example.net     (390)417-1635x3010    15-04-1923   
..                             ...                    ...           ...   
995         lyonsdaisy@example.net           021.775.2933    05-01-1959   
996        dariusbryan@example.com   001-149-710-7799x721    06-10-2001   
997         georgechan@example.org  +1-750-774-4128x33265    13-05-1918   
998            wanda04@example.net          (915)292-2254    31-08-1971   
999        deannablack@example.org     079.752.5424x67259    24-01-1947   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000  
..                               ...     ...  
995                Personnel officer   90000  
996          Education administrator   50000  
997  Commercial/residential surveyor   60000  
998                 Ambulance person  100000  
999       Nurse, learning disability   90000  

[1000 rows x 10 columns]

In [69]:
import pandas as pd

# Sample data
data = {
    'Phone': ['+1-234-567-8901', '234.567.8902', '(234) 567-8903', '2345678904']
}


df = pd.DataFrame(data) # Create DataFrame


df['Phone'] = df['Phone'].replace(r'\D+', '', regex=True) # Remove non-numeric characters

# Convert to numeric data type
df['Phone'] = pd.to_numeric(df['Phone'], errors='coerce')

# Display the DataFrame
print("Cleaned DataFrame:")
print(df)



Cleaned DataFrame:
         Phone
0  12345678901
1   2345678902
2   2345678903
3   2345678904

Column Attributes and Data Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phone   4 non-null      int64
dtypes: int64(1)
memory usage: 160.0 bytes
None


In [71]:
# Display column attributes and data types

print("\nColumn Attributes and Data Types:")
print(df.info())



Column Attributes and Data Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Phone   4 non-null      int64
dtypes: int64(1)
memory usage: 160.0 bytes
None


In [ ]:
8.  Perform the following tasks using people dataset:

 a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

 b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

 c) Display the first 10 rows of the filtered dataset.

 d) Extract the ‘Salary’' column as a Series and display its last 5 valuess.

In [73]:
# a) Read the 'data.csv' file using pandas, skipping the first 50 rows.

import pandas as pd



df = pd.read_csv('People Data.csv', skiprows=50)

# Display the first few rows of the DataFrame to confirm
print(df.head())


   50  afF3018e9cdd1dA     George  Mercer  Female  \
0  51  CccE5DAb6E288e5         Jo  Zavala    Male   
1  52  DfBDc3621D4bcec     Joshua   Carey  Female   
2  53  f55b0A249f5E44D     Rickey   Hobbs  Female   
3  54  Ed71DcfaBFd0beE      Robyn  Reilly    Male   
4  55  FDaFD0c3f5387EC  Christina  Conrad    Male   

  douglascontreras@example.net    +1-326-669-0118x4341  11-09-1941  \
0         pamela64@example.net  001-859-448-9935x54536  23-11-1992   
1    dianashepherd@example.net    001-274-739-8470x814  07-01-1915   
2    ingramtiffany@example.org        241.179.9509x498  01-07-1910   
3   carriecrawford@example.org       207.797.8345x6177  27-07-1982   
4   fuentesclaudia@example.net    001-599-042-7428x143  06-01-1998   

  Human resources officer   70000  
0            Nurse, adult   80000  
1     Seismic interpreter   70000  
2               Barrister   60000  
3    Engineer, structural  100000  
4         Producer, radio   50000  


In [77]:
# b) Only read the columns: 'Last Name', ‘Gender’,’Email’,‘Phone’ and ‘Salary’ from the file.

import pandas as pd

# Specify the columns to read
columns_to_read = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']

# Read the CSV file, selecting only the specified columns
df = pd.read_csv('People Data.csv', usecols=columns_to_read)

# Display the first few rows of the DataFrame to confirm
print(df.head())



  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000


In [79]:
# c) Display the first 10 rows of the filtered dataset.

import pandas as pd

# Specify the columns to read
columns_to_read = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']

# Read the CSV file, selecting only the specified columns
df = pd.read_csv('People Data.csv', usecols=columns_to_read)

# Display the first 10 rows of the DataFrame
print(df.head(10))


  Last Name  Gender                          Email               Phone  Salary
0   Mahoney    Male            pwarner@example.org        857.139.8239   90000
1    Rivers  Female  fergusonkatherine@example.net                 NaN   80000
2    Lowery  Female            fhoward@example.org       (599)782-0605   50000
3    Hooper    Male          zjohnston@example.com                 NaN   65000
4      Rice  Female               elin@example.net  (390)417-1635x3010  100000
5  Caldwell    Male          kaitlin13@example.net          8537800927   50000
6   Hoffman    Male         jeffharvey@example.com   093.655.7480x7895   60000
7  Andersen    Male           alicia33@example.org          4709522945   65000
8      Mays    Male             jake50@example.com        013.820.4758   50000
9  Mitchell    Male      lanechristina@example.net  (560)903-5068x4985   50000


In [80]:
#d) Extract the ‘Salary’' column as a Series and display its last 5 valuess.

import pandas as pd

# Specify the columns to read
columns_to_read = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']

# Read the CSV file, selecting only the specified columns
df = pd.read_csv('People Data.csv', usecols=columns_to_read)

# Extract the 'Salary' column as a Series
salary_series = df['Salary']

# Display the last 5 values of the 'Salary' Series
print(salary_series.tail(5))



995     90000
996     50000
997     60000
998    100000
999     90000
Name: Salary, dtype: int64


In [ ]:
9. Filter and select rows from the People_Dataset, where the “Last Name' column contains the name 'Duke', 
'Gender' column contains the word Female and ‘salary’ should be less than 85000

In [82]:
import pandas as pd

# Specify the columns to read
columns_to_read = ['Last Name', 'Gender', 'Email', 'Phone', 'Salary']

# Read the CSV file, selecting only the specified columns
df = pd.read_csv('People Data.csv', usecols=columns_to_read)

# Apply filters
filtered_df = df[
    (df['Last Name'].str.contains('Duke', case=False, na=False)) &
    (df['Gender'].str.contains('Female', case=False, na=False)) &
    (df['Salary'] < 85000)
]

# Display the filtered DataFrame
print(filtered_df)


    Last Name  Gender                     Email                   Phone  \
45       Duke  Female       diana26@example.net  001-366-475-8607x04350   
210      Duke  Female       robin78@example.com            740.434.0212   
457      Duke  Female  perryhoffman@example.org     +1-903-596-0995x489   
729      Duke  Female   kevinkramer@example.net            982.692.6257   

     Salary  
45    60000  
210   50000  
457   50000  
729   70000  


In [ ]:
10. Create a 7"5 Dataframe in Pandas using a series generator from 35 random integers between 1 to 6?

In [84]:
import pandas as pd
import numpy as np

# Generate 35 random integers between 1 and 6
random_integers = np.random.randint(1, 7, size=35)

# Reshape the array into a 7x5 DataFrame
df = pd.DataFrame(random_integers.reshape(7, 5), columns=['A', 'B', 'C', 'D', 'E'])

# Display the DataFrame
print(df)



   A  B  C  D  E
0  5  4  2  2  1
1  1  3  6  4  1
2  5  3  1  3  5
3  3  5  3  6  4
4  6  2  5  6  1
5  6  2  6  3  1
6  1  3  3  5  1


In [ ]:
11. Create two different Series, each of length 50, with the following criteria:

a) The first Series should contain random numbers ranging from 10 to 50.

b) The second Series should contain random numbers ranging from 100 to 1000.

c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2',
etc&

In [86]:
#a) The first Series should contain random numbers ranging from 10 to 50.

import pandas as pd
import numpy as np

# Create a Series with 50 random integers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# Display the Series
print(series1)


0     34
1     25
2     34
3     26
4     21
5     36
6     35
7     22
8     19
9     43
10    13
11    22
12    23
13    50
14    42
15    11
16    23
17    43
18    10
19    49
20    42
21    21
22    12
23    26
24    17
25    50
26    41
27    48
28    42
29    25
30    11
31    16
32    23
33    41
34    49
35    50
36    42
37    34
38    10
39    15
40    47
41    12
42    10
43    18
44    50
45    41
46    31
47    41
48    11
49    47
dtype: int64


In [89]:
#b) The second Series should contain random numbers ranging from 100 to 1000.

import pandas as pd
import numpy as np

# Create the first Series with 50 random integers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# Create the second Series with 50 random integers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, size=50))

# Display the Series
print("First Series:")
print(series1)

print("\nSecond Series:")
print(series2)



First Series:
0     40
1     14
2     17
3     11
4     16
5     21
6     48
7     14
8     32
9     15
10    48
11    33
12    39
13    18
14    40
15    25
16    39
17    27
18    47
19    21
20    30
21    34
22    26
23    45
24    17
25    34
26    37
27    31
28    24
29    38
30    27
31    11
32    39
33    36
34    18
35    48
36    48
37    20
38    18
39    22
40    49
41    28
42    22
43    35
44    10
45    41
46    15
47    35
48    44
49    33
dtype: int64

Second Series:
0     147
1     252
2     136
3     298
4     811
5     993
6     551
7     270
8     911
9     187
10    367
11    818
12    178
13    597
14    726
15    749
16    203
17    450
18    847
19    219
20    418
21    925
22    501
23    517
24    453
25    384
26    314
27    702
28    870
29    756
30    345
31    378
32    525
33    759
34    517
35    517
36    591
37    132
38    937
39    414
40    851
41    355
42    395
43    932
44    277
45    127
46    120
47    913
48    686
49    305
dtype: 

In [90]:
#c) Create a DataFrame by joining these Series by column, and, change the names of the columns to 'col1', 'col2',
#etc&
import pandas as pd
import numpy as np

# Create the first Series with 50 random integers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# Create the second Series with 50 random integers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, size=50))

# Combine the Series into a DataFrame by columns
df = pd.DataFrame({
    'col1': series1,
    'col2': series2
})

# Display the DataFrame
print(df)



    col1  col2
0     48   909
1     42   646
2     19   101
3     48   893
4     44   945
5     26   665
6     21   990
7     28   262
8     30   687
9     36   941
10    30   825
11    29   117
12    30   697
13    45   918
14    48   329
15    20   407
16    29   826
17    50   402
18    31   764
19    37   894
20    33   516
21    14   944
22    12   502
23    17   659
24    20   657
25    20   221
26    49   202
27    25   223
28    37   206
29    48   792
30    45   841
31    23   971
32    17   900
33    46   435
34    30   365
35    33   306
36    35   511
37    18   588
38    41   584
39    18   344
40    48   215
41    40   539
42    32   389
43    50   119
44    45   826
45    37   440
46    18   901
47    33   137
48    18   296
49    26   149


In [ ]:
12. Perform the following operations using people data set:

a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

b) Delete the rows containing any missing values.

d) Print the final output also.

In [95]:
#a) Delete the 'Email', 'Phone', and 'Date of birth' columns from the dataset.

import pandas as pd

# Load the dataset (adjust the filename/path as needed)
df = pd.read_csv('People Data.csv')

# a) Delete the 'Email', 'Phone', and 'Date of birth' columns
df = df.drop(columns=['Email', 'Phone', 'Date of birth'])


print(df)


     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000

In [97]:
# b) Delete the rows containing any missing values
df = df.dropna()

# d) Print the final DataFrame
print(df)

     Index          User Id First Name Last Name  Gender  \
0        1  8717bbf45cCDbEe     Shelia   Mahoney    Male   
1        2  3d5AD30A4cD38ed         Jo    Rivers  Female   
2        3  810Ce0F276Badec     Sheryl    Lowery  Female   
3        4  BF2a889C00f0cE1    Whitney    Hooper    Male   
4        5  9afFEafAe1CBBB9    Lindsey      Rice  Female   
..     ...              ...        ...       ...     ...   
995    996  fedF4c7Fd9e7cFa       Kurt    Bryant  Female   
996    997  ECddaFEDdEc4FAB      Donna     Barry  Female   
997    998  2adde51d8B8979E      Cathy  Mckinney  Female   
998    999  Fb2FE369D1E171A   Jermaine    Phelps    Male   
999   1000  8b756f6231DDC6e        Lee      Tran  Female   

                           Job Title  Salary  
0                  Probation officer   90000  
1                             Dancer   80000  
2                               Copy   50000  
3           Counselling psychologist   65000  
4                Biomedical engineer  100000

In [ ]:
13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the
following tasks using Matplotlib and NumPy:

a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.

b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.

c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.

e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

f) Display a legend for the scatter plot, the horizontal line, and the vertical line.

In [131]:
#a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'.


import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o')

# Set title and labels
plt.title('Scatter Plot of Random Values')
plt.xlabel('x values')
plt.ylabel('y values')

# Show the plot
plt.show()

In [132]:
#b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'.


import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Set title and labels
plt.title('Scatter Plot with Horizontal Line')
plt.xlabel('x values')
plt.ylabel('y values')

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [133]:
#c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'.

import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Set title and labels
plt.title('Scatter Plot with Horizontal and Vertical Lines')
plt.xlabel('x values')
plt.ylabel('y values')

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [134]:
#d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'.


import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Set title and labels
plt.title('Scatter Plot with Horizontal and Vertical Lines')
plt.xlabel('X-axis')  # Label x-axis
plt.ylabel('Y-axis')  # Label y-axis

# Add a legend
plt.legend()

# Show the plot
plt.show()

In [135]:
#e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'.

import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Set title and labels
plt.title('Advanced Scatter Plot of Random Values')  # Title of the plot
plt.xlabel('X-axis')  # Label x-axis
plt.ylabel('Y-axis')  # Label y-axis

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [137]:
#f Display a legend for the scatter plot, the horizontal line, and the vertical line.

import numpy as np
import matplotlib.pyplot as plt

# Generate random float values between 0 and 1
x = np.random.rand(100)
y = np.random.rand(100)

# Create a scatter plot
plt.scatter(x, y, color='red', marker='o', label='Scatter Points')

# Add a horizontal line at y = 0.5
plt.axhline(y=0.5, color='blue', linestyle='--', label='y = 0.5')

# Add a vertical line at x = 0.5
plt.axvline(x=0.5, color='green', linestyle=':', label='x = 0.5')

# Set title and labels
plt.title('Advanced Scatter Plot of Random Values')  # Title of the plot
plt.xlabel('X-axis')  # Label x-axis
plt.ylabel('Y-axis')  # Label y-axis

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [ ]:
14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and
Perform the following tasks using Matplotlib:
Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:


a) Plot the 'Temperature' and 'Humidity' on the same lot with different y-axes (left y-axis for 'Temerature' and
right y-axis for 'Humidity').

b) Label the x-axis as 'Date'.

c) Set the title of the plot as 'Temperature and Humidity Over Time'.

In [136]:
#a. import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

# Create a time-series dataset
np.random.seed(0)  # For reproducibility
dates = pd.date_range(start='2024-01-01', periods=100, freq='D')
temperature = np.random.normal(loc=20, scale=5, size=len(dates))  # Temperature data
humidity = np.random.normal(loc=60, scale=10, size=len(dates))  # Humidity data

# Create a DataFrame
df = pd.DataFrame({
    'Date': dates,
    'Temperature': temperature,
    'Humidity': humidity
})

# Plot 'Temperature' and 'Humidity' on the same plot with different y-axes
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot 'Temperature' on the left y-axis
color = 'tab:red'
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature', color=color)
ax1.plot(df['Date'], df['Temperature'], color=color, label='Temperature')
ax1.tick_params(axis='y', labelcolor=color)

# Create a second y-axis to plot 'Humidity'
ax2 = ax1.twinx()  
color = 'tab:blue'
ax2.set_ylabel('Humidity', color=color)  
ax2.plot(df['Date'], df['Humidity'], color=color, label='Humidity')
ax2.tick_params(axis='y', labelcolor=color)

# Add title and legends
plt.title('Temperature and Humidity Over Time')
fig.tight_layout()  # Adjust layout to make room for the second y-axis

# Show plot
plt.show()




In [130]:
#b. 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create a time-series dataset


In [129]:
#c) Set the title of the plot as 'Temperature and Humidity Over Time'.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Create a time-series dataset
np.random.seed(0)  # For reproducibility
dates = pd.date_range(start='2024-01-01', periods=100, freq='D')
temperature = np.random.normal(loc=20, scale=5, size=len(dates))  # Temperature data
humidity = np.random.normal(loc=60, scale=10, size=len(dates))  # Humidity data

# Create a DataFrame
df = pd.DataFrame({
    'Date': dates,
    'Temperature': temperature,
    'Humidity': humidity
})

# Plot 'Temperature' and 'Humidity' on the same plot with different y-axes
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot 'Temperature' on the left y-axis
color = 'tab:red'
ax1.set_xlabel('Date')  # Label x-axis
ax1.set_ylabel('Temperature', color=color)
ax1.plot(df['Date'], df['Temperature'], color=color, label='Temperature')
ax1.tick_params(axis='y', labelcolor=color)

# Create a second y-axis to plot 'Humidity'
ax2 = ax1.twinx()  
color = 'tab:blue'
ax2.set_ylabel('Humidity', color=color)  
ax2.plot(df['Date'], df['Humidity'], color=color, label='Humidity')
ax2.tick_params(axis='y', labelcolor=color)

# Add title and legends
plt.title('Temperature and Humidity Over Time')  # Title of the plot
fig.tight_layout()  # Adjust layout to make room for the second y-axis

# Show plot
plt.show()



In [ ]:
15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following
tasks using Matplotlib:

a) Plot a histogram of the data with 30 bins.

b) Overlay a line plot representing the normal distribution's probability density function (PDF).

c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

d) Set the title of the plot as 'Histogram with PDF Overlay'.

In [128]:
# a. Plot a histogram of the data with 30 bins.

import numpy as np
import matplotlib.pyplot as plt

# Generate 1000 samples from a normal distribution
np.random.seed(0)  # For reproducibility
data = np.random.normal(loc=0, scale=1, size=1000)  # Normal distribution with mean=0 and std=1

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, edgecolor='black', alpha=0.7)

# Set title and labels
plt.title('Histogram of Normally Distributed Data')
plt.xlabel('Value')
plt.ylabel('Frequency')

# Show the plot
plt.show()


In [127]:
# b. Overlay a line plot representing the normal distribution's probability density function (PDF).


import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate 1000 samples from a normal distribution
np.random.seed(0)  # For reproducibility
data = np.random.normal(loc=0, scale=1, size=1000)  # Normal distribution with mean=0 and std=1

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, edgecolor='black', alpha=0.6, label='Histogram')

# Calculate the PDF of the normal distribution
xmin, xmax = plt.xlim()  # Get the range of x values for the plot
x = np.linspace(xmin, xmax, 100)  # Generate x values
pdf = norm.pdf(x, loc=0, scale=1)  # Compute the PDF

# Overlay the PDF line plot
plt.plot(x, pdf, 'k--', label='Normal Distribution PDF')  # 'k--' for black dashed line

# Set title and labels
plt.title('Histogram and PDF of Normally Distributed Data')
plt.xlabel('Value')
plt.ylabel('Density')

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [126]:
#d) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate 1000 samples from a normal distribution
np.random.seed(0)  # For reproducibility
data = np.random.normal(loc=0, scale=1, size=1000)  # Normal distribution with mean=0 and std=1

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, edgecolor='black', alpha=0.6, label='Histogram')

# Calculate the PDF of the normal distribution
xmin, xmax = plt.xlim()  # Get the range of x values for the plot
x = np.linspace(xmin, xmax, 100)  # Generate x values
pdf = norm.pdf(x, loc=0, scale=1)  # Compute the PDF

# Overlay the PDF line plot
plt.plot(x, pdf, 'k--', label='Normal Distribution PDF')  # 'k--' for black dashed line

# Set title and labels
plt.title('Histogram and PDF of Normally Distributed Data')
plt.xlabel('Value')  # Label x-axis
plt.ylabel('Frequency/Probability')  # Label y-axis

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [125]:
# c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'.

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Generate 1000 samples from a normal distribution
np.random.seed(0)  # For reproducibility
data = np.random.normal(loc=0, scale=1, size=1000)  # Normal distribution with mean=0 and std=1

# Plot a histogram of the data with 30 bins
plt.hist(data, bins=30, density=True, edgecolor='black', alpha=0.6, label='Histogram')

# Calculate the PDF of the normal distribution
xmin, xmax = plt.xlim()  # Get the range of x values for the plot
x = np.linspace(xmin, xmax, 100)  # Generate x values
pdf = norm.pdf(x, loc=0, scale=1)  # Compute the PDF

# Overlay the PDF line plot
plt.plot(x, pdf, 'k--', label='Normal Distribution PDF')  # 'k--' for black dashed line

# Set title and labels
plt.title('Histogram and PDF of Normally Distributed Data')
plt.xlabel('Value')  # Label x-axis
plt.ylabel('Frequency/Probability')  # Label y-axis

# Add a legend
plt.legend()

# Show the plot
plt.show()


In [ ]:
18. With Bokeh, plot a line chart of sine wave function, add grid lines, label the azes, abd set the title as 'Sine Wave Function'

In [ ]:

from bokeh.plotting import figure, show
from bokeh.io import output_notebook
import numpy as np

# Output to notebook (remove this if using a different output method)
output_notebook()

# Generate data for the sine wave
x = np.linspace(0, 4 * np.pi, 100)  # X values from 0 to 4*pi
y = np.sin(x)  # Y values as the sine of X

# Create a Bokeh figure
p = figure(title="Sine Wave Function", x_axis_label='X', y_axis_label='Y', width=800, height=400)

# Add a line renderer
p.line(x, y, legend_label="Sine Wave", line_width=2)

# Add grid lines (grid is enabled by default, but you can customize it if needed)
p.grid.grid_line_color = 'gray'
p.grid.grid_line_alpha = 0.5

# Show the plot
show(p)

In [ ]:
19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their
values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical
Bar Chart'8

In [ ]:
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool, LinearColorMapper
from bokeh.palettes import Viridis256
import pandas as pd
import numpy as np

# Generate random categorical data
np.random.seed(0)  # For reproducibility
categories = [f'Category {i+1}' for i in range(10)]
values = np.random.randint(10, 100, size=len(categories))

# Create a DataFrame
df = pd.DataFrame({
    'Category': categories,
    'Value': values
})

# Create a ColumnDataSource
source = ColumnDataSource(df)

# Create a color mapper based on values
mapper = LinearColorMapper(palette=Viridis256, low=min(values), high=max(values))

# Create a Bokeh figure
p = figure(x_range=df['Category'], plot_height=400, plot_width=700, title='Random Categorical Bar Chart',
           toolbar_location=None, tools='')

# Add a bar renderer
p.vbar(x='Category', top='Value', width=0.5, source=source, legend_field='Category',
       color={'field': 'Value', 'transform': mapper}, line_color='white')

# Add hover tooltips
hover = HoverTool()
hover.tooltips = [("Category", "@Category"), ("Value", "@Value")]
p.add_tools(hover)

# Label the axes and set the title
p.xaxis.axis_label = 'Category'
p.yaxis.axis_label = 'Value'
p.xaxis.major_label_orientation = "vertical"
p.title.text_font_size = '16pt'

# Customize the plot appearance
p.grid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = 'top_left'
p.legend.orientation = 'horizontal'

# Show the plot
show(p)


In [ ]:
20.  Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as
'Simple Line Plot'8

In [ ]:
import plotly.graph_objects as go
import numpy as np

# Generate random data
np.random.seed(0)  # For reproducibility
x = np.arange(100)  # Array of 100 integers from 0 to 99
y = np.random.randn(100)  # Array of 100 random values from a normal distribution

# Create the line plot
fig = go.Figure()

# Add a trace for the line plot
fig.add_trace(go.Scatter(x=x, y=y, mode='lines', name='Random Data'))

# Update layout with labels and title
fig.update_layout(
    title='Simple Line Plot',
    xaxis_title='X-axis',
    yaxis_title='Y-axis'
)

# Show the plot
fig.show()


In [ ]:
21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set
the title as 'Interactive Pie Chart'.

In [ ]:
import plotly.graph_objects as go
import numpy as np

# Generate random data
np.random.seed(0)  # For reproducibility
categories = [f'Category {i+1}' for i in range(10)]
values = np.random.randint(10, 100, size=len(categories))

# Create the pie chart
fig = go.Figure(data=[go.Pie(
    labels=categories,
    values=values,
    textinfo='label+percent',  # Show label and percentage
    hole=0.3  # Add a hole to create a donut chart; set to 0 for a standard pie chart
)])

# Update layout with title
fig.update_layout(
    title='Interactive Pie Chart'
)

# Show the plot
fig.show()
